spring.application.name=backend

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JWT
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

# TMDB
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.token=${TMDB_API_TOKEN}
tmdb.read.token=${TMDB_READ_TOKEN}
