spring.application.name=backend

# DATABASE (environment)
spring.datasource.url=${DB_URL}
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

###H2
#spring.datasource.url=jdbc:h2:mem:filmly
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (environment)
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

#TMDB
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.token=${TMDB_API_TOKEN}
tmdb.read.token=${TMDB_READ_TOKEN}

#Server
server.port=${PORT:8080}
