server.forward-headers-strategy=framework

spring.datasource.url=${DB_URL}
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update
